obstacle_gate:
  ros__parameters:
    scan_topic: "/scan"
    cmd_in_topic: "/cmd_vel_raw"
    cmd_out_topic: "/cmd_vel"
    min_ignore_radius_m: 0.30
    front_sector_deg: 60.0
    rear_sector_deg: 60.0
    stop_distance_m: 0.40
    slow_distance_m: 0.60
    angle_masks_deg: [120.0, 250.0]  # example brackets; tune for your chassis
    publish_rate_hz: 30.0
    scan_timeout_s: 0.5
    cmd_timeout_s: 0.5
